<template>
  <v-layout>
    <v-flex class="text-center">
      <div>
        <p>Part1</p>
        <p>
          横断歩道では、渡る人が待っている場合は残らなければならない
        </p>
        <v-btn
          color="red"
          nuxt
          to="/part1ans"
        >
          ○
        </v-btn>
        <v-btn
          color="blue"
          nuxt
          to="/part1ans"
          style="margin-left:10px"
        >
          ×
        </v-btn>
      </div>
    </v-flex>
  </v-layout>
</template>
